### ISSUE TITLE
Host visual ID at Identihub

### ISSUE THREAD

**Issue by rskikuli** [CityZenApp/Project-Management#10]
In case we do not have already hosted our visual ID at Identihub, we need to host it the soonest and also promote it a bit through our social media (ping @marianaballa ). It also needs to be visible at our website (ping @sidorelauku ).

**Comment by rskikuli** [comment]
@AnXh3L0 please an update on this. @sidorelauku after this is done please add link to the press corner. Ideal deadline: 28.02.2018.

**Comment by AnXh3L0** [comment]
Yes, the Identihub page of the project is up and ready here: https://demo.identihub.co/project/cityzen

**Comment by rskikuli** [comment]
![cityzen_screenshot from 2018-06-02 13-48-00](https://user-images.githubusercontent.com/17770262/40874224-f270f6ca-666c-11e8-832c-ab03cef5f857.png)
@AnXh3L0 there is something weird going on with the logos. Have a look at the screenshot.

**Comment by AnXh3L0** [comment]
It should be fixed now, please check again.

**Comment by rskikuli** [comment]
Yeap it is better now. Documented here: https://github.com/CityZenApp/Project-Management/wiki/Visual-materials and also at the credits: http://cityzenapp.co/credits/. Thank you! closing this.

**Comment by rskikuli** [comment]
Yeap it is better now. Documented here: https://github.com/CityZenApp/Project-Management/wiki/Visual-materials and also at the credits: http://cityzenapp.co/credits/. Thank you! closing this.
