### ISSUE TITLE
Website: fix the redirect to the homepage

### ISSUE THREAD

**Issue by rskikuli** [CityZenApp/Project-Management#27]
While on one of the blogposts, when you click on the CityZen logo on the upper right corner it sends to a 404 error page. Example: http://cityzenapp.co/2018/01/31/localization.html.

Deadline 30.03.2018.

**Comment by sidorelauku** [comment]
@rskikuli do you still have this issue? as to me it seems to be ok.

**Comment by rskikuli** [comment]
This seems to be ok now. Many thanks @sidorelauku ! Closing this now.
