### ISSUE TITLE
Blog: CityZen of the month April 2018

### ISSUE THREAD

**Issue by rskikuli** [CityZenApp/Project-Management#28]
After the initial idea #25 got some traction from @marianaballa we are planning to continue the series in the next months. People can also be nominated here at GitHub, which will involve also the community.
Here are the proposed questions:

- Please introduce yourself;
- When and how did you discover CityZen?
- Why did you become a CityZen? What motivates you?
- In what field do you contribute more (community, documentation, development, community development, blockchain?)?
- What is your biggest achievement as a CityZen (contributor)?
- What is one of the CityZen features you can't wait to see?
- Do you have contact with other CityZens?
- Are you also an OpenStreetMap contributor?
- To conclude, is there anything else you want to mention?

Please propose the CityZen of the month in the comment section.

**Comment by marianaballa** [comment]
For the month of March Andy was the contributor of the month.

For April, I'd like to nominate Elio Qoshi. He has helped a lot with his design skills and has dedicated a lot of energy on the project.

**Comment by rskikuli** [comment]
+1 with @marianaballa . If you have proposals please share here.

**Comment by AndyScherzinger** [comment]
:+1: for the April proposal of @marianaballa

**Comment by marianaballa** [comment]
Blogpost with Elio's interview was published today. You can find it here: http://cityzenapp.co/2018/04/30/cityzen-of-the-month-elio-qoshi.html
