### ISSUE TITLE
 Blog: CityZen of the month May 2018

### ISSUE THREAD

**Issue by rskikuli** [CityZenApp/Project-Management#31]
Following the initial idea #25 we are opening the proposals from the community to nominate CityZen of the month for May 2018. 
Here are the proposed questions:

- Please introduce yourself;
- When and how did you discover CityZen?
- Why did you become a CityZen? What motivates you?
- In what field do you contribute more (community, documentation, development, community development, blockchain?)?
- What is your biggest achievement as a CityZen (contributor)?
- What is one of the CityZen features you can't wait to see?
- Do you have contact with other CityZen(s)?
- Are you also an OpenStreetMap contributor? If ytes, what drives you to contribute to OSM?
- To conclude, is there anything else you want to mention?

If you think that there are members of the community (CityZen(s)) that needs to be recognizer from the community, please propose them here.

**Comment by marianaballa** [comment]
As the next CityZen of the Month I would like to nominate @sidorelauku. She has contributed a lot at the project and I think she deserves to be the next person to be featured on the blog. :)

**Comment by rskikuli** [comment]
I also support the proposal. Sidorela has been very active not only the last months, but from day one of the project.  Hopefully more community members will agree with the proposal.

**Comment by rskikuli** [comment]
Hey @sidorelauku waiting for your responses :)

**Comment by rskikuli** [comment]
Blog post is online: http://cityzenapp.co/2018/06/15/cityzen-of-the-month-sidorela-uku.html. Thank you @sidorelauku and @marianaballa for your engagement. Closing this.
