### ISSUE TITLE
Apply for Digital Impact Alliance grant

### ISSUE THREAD

**Issue by rskikuli** [CityZenApp/Project-Management#44]
There is an interesting grant that might help us improve our project. The DIAL Open Source Center’s Catalytic Grant program is an offering of financial support for free & open source software projects working in the humanitarian response & international development sectors. These grants are intended to support types of work that have traditionally been neglected or unfinished by these projects for various reasons. @nafieshehu wanna get involved? 
Link with details: http://www.osc.dial.community/grants.html

Deadline November 2018.

**Comment by nafieshehu** [comment]
@rskikuli I think we should try to apply for this round because the deadline is extended until June 15. Had a look at the questions, will update you tomorrow.

**Comment by nafieshehu** [comment]
Working here for the application process: https://pad.openlabs.cc/p/Digital_Impact_Alliance_grant

**Comment by rskikuli** [comment]
Application send. Thank you @nafieshehu . Closing this.
