### ISSUE TITLE
Unicef Innovation Fund application

### ISSUE THREAD

**Issue by rskikuli** [CityZenApp/Project-Management#52]
UNICEF's Innovation (Venture) Fund is a newly established, non-thematic, pooled fund which has been specifically designed to finance early stage, open-source technology that can benefit children. The core motivation of the Innovation Fund is to identify "clusters" or portfolios of initiatives around emerging technology - so that UNICEF can both shape markets and also learn about and guide these technologies to benefit children. The initiative invests in solutions that can impact the lives of the most vulnerable children. 
We find these solutions clustered around $100 billion industries in frontier technology spaces, such as: blockchain, UAVs, virtual and augmented reality, machine learning, quantum computing, genetic engineering, Internet of Things, artificial intelligence, nano-satellites and human dynamics.
This seems like a good opportunity for us to apply and get some support. Website: https://unicefinnovationfund.org/#/about

Deadline for draft application: 06.07.2018 
Deadline for submission: 10.07.2018

**Comment by nafieshehu** [comment]
Hi,

Will work on the application process and will keep you informed.

Thanks,
Nafie

**Comment by rskikuli** [comment]
The application is done by @silvaarapi . Maybe it needs review also from you @nafieshehu ? Anyway, closing this to remove the clutter.
