### ISSUE TITLE
Add CityZen at droid-break.info

### ISSUE THREAD

**Issue by rskikuli** [CityZenApp/Project-Management#53]
Droid-Break is a list of free and open source Android apps inspired by Prism-Break. The purpose of the project is to show high quality alternatives to the big proprietary solutions.
Would be great to add also CityZen to the list of apps that are displayed there. Here are the instructions about this: 

> If you think an app should be added please write an email, a tweet, a Disqus comment, or fork the project on GitHub and make a pull request.

Website of the project can be found here: https://droid-break.info/

Deadline: 15.07.2018

**Comment by AndyScherzinger** [comment]
@rskikuli PR has been opened: https://github.com/droidbreak/droidbreak.github.io/pull/64

**Comment by rskikuli** [comment]
Thanks @AndyScherzinger . Now we wait for the issue from droidbreak to be closed right?  Let me know if additional information is needed from my side.

**Comment by AndyScherzinger** [comment]
Exactly @rskikuli - so let's wait and see.

**Comment by rskikuli** [comment]
It seems like they did not update it. What do you think is the best way to ping them @AndyScherzinger ?

**Comment by AndyScherzinger** [comment]
No idea really. I did ping the owner via the corresponding twitter account but never got any reaction :(

**Comment by repat** [comment]
Sorry I've been super busy lately and also on vacation (on which I don't take my laptop ;)). PR merged :)

**Comment by AndyScherzinger** [comment]
Thanks a lot @repat, highly appreciate your efforts ❤️

**Comment by rskikuli** [comment]
Thank you guys. Closing this now.
