### ISSUE TITLE
Transfering management of the project to a company

### ISSUE THREAD

**Issue by rskikuli** [CityZenApp/Project-Management#56]
Dear active contributors, during the last weeks there have been many instances when individuals or group of people have abused the free open source license we are using for our project. The actual version of CityZen is been created through a lot of work and investment of a small team that has dedicated countless hours to the project. It seems that there are people out there that do not respect our efforts and also do not care about what is clearly written in the Mozilla Public License we are using. 
Another reason I opened this issue, in hope to generate a discussion, is the fact that based on the vision of having in-app payments (manly through crypto-currencies) we will need a fiscal entity for logistical reasons. The initial thought was that a fiscal entity is not needed since all the transactions would be using crypto. Unfortunately, based on the research so far, some businesses that accept crypto-payments still need to have a fiscal entity such as a company for any kind of transaction of any kind. 
Having said this, I think that it is important to connect the project with a company. This will allow us to:

- fight back whenever there is a case where individuals or companies do not respect the license of the project;
- manage the relationship with the companies that will accept payments through the app. 

Ehat do you think of this?.Your feedback on this is highly appreciated.

**Time for community consultation:** 15.08.2018
**Deadline for decision based on community feedback:** 20.08.2018

Thank you!

**Comment by marianaballa** [comment]
Redon I read carefully your notes and I can see your concerns. To me as a contributor wouldn't make much of a difference if the management of the project will be transferred to an established company. 
As long as the company that will foster the CityZen project shares the same "philosophy" I don't think that will be a problem.

**Comment by samtuke** [comment]
@rskikuli Sorry to hear about the license violations. What is the legal owner of the copyright of the app currently, and how would transferring copyright to a company make enforcement easier?

The owner of the copyright and the recipient of in-app payments does not need to be the same entity.

**Comment by rskikuli** [comment]
Thanks for your valuable feedback Sam. Regarding the copyright ownership: I have had the initial idea and vision of the project and have worked a lot to implement the vision. Many people have been involved in a way or the other some more intensively and other less, some people where active in the beginning and did not get involved after a while and others have been quite active only lately. Based on the incident with the copycat app on Play store it seems quite important to clarify the copyright ownership of the project. 
The idea of the proposal is that specifying that the project is managed legally under company X helps the case when communicating with companies like Google when disputes such as the one I described. At the same time, managing the payment processes through a company and also paying for third party costs (servers, promo materials etc) is easier and logistically makes more sense  as a company than me personally doing it. 
In a few words, even if copyright management and payment logistics can be handled by two or more different entities or individuals like me it makes more sense in the 'eyes' of third parties to manage these issues from a single company/entity. 
Does this answer your questions @samtuke ?

**Comment by jdnrg** [comment]
A foundation might make sense for the same goals

**Comment by rskikuli** [comment]
We have now a decision on this. Thanks everybody on the constructive online and offline discussions. Closing this.
